In [6]:
import torch
import numpy as np

In [5]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [7]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [8]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [10]:
torch.tensor(data)

tensor([1, 2, 3])

In [11]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [12]:
torch.from_numpy(data)

tensor([1, 2, 3])

In [13]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [14]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [16]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [17]:
torch.rand(2,2)

tensor([[0.5801, 0.9236],
        [0.4970, 0.0592]])

In [19]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [20]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [21]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int64
torch.int64
torch.int64


In [23]:
torch.get_default_dtype()

torch.float32

In [25]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3])

In [26]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

In [27]:
torch.tensor(np.array([1,2,3]),dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

## Memory  : Sharing vs Copying

In [28]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [29]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [31]:
data[0] = 0
data[1] = 0
data[2] = 0

In [32]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [33]:
print(t3)
print(t4)

tensor([0, 0, 0])
tensor([0, 0, 0])


## Reshaping Explained - Pythorch Tensor for Deep Learning

In [34]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [35]:
t.size()

torch.Size([3, 4])

In [37]:
t.shape

torch.Size([3, 4])

In [39]:
len(t.shape)

2

In [41]:
torch.tensor(t.shape).prod()

tensor(12)

In [43]:
t.numel()
# number of element

12

In [44]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [45]:
t.reshape(2,3,2)

tensor([[[1., 1.],
         [1., 1.],
         [2., 2.]],

        [[2., 2.],
         [3., 3.],
         [3., 3.]]])

In [48]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [49]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [51]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [52]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [53]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])